// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BanPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteLayoutPreset(arg1:string):Promise<void>;

export function GetActiveTiles():Promise<Array<string>>;

export function GetCustomCommands():Promise<Array<string>>;

export function GetLayoutPresets():Promise<Array<models.LayoutPreset>>;

export function GetPlayers(arg1:string):Promise<Array<models.Player>>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function KickPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function SaveActiveTiles(arg1:Array<string>):Promise<void>;

export function SaveCustomCommands(arg1:Array<string>):Promise<void>;

export function SaveLayoutPreset(arg1:string,arg2:string):Promise<void>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;
