// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptEula(arg1) {
  return window['go']['main']['App']['AcceptEula'](arg1);
}

export function BackupWorld(arg1, arg2) {
  return window['go']['main']['App']['BackupWorld'](arg1, arg2);
}

export function BanPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['BanPlayer'](arg1, arg2, arg3);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function BrowseJarFile() {
  return window['go']['main']['App']['BrowseJarFile']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DeleteBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteBackup'](arg1, arg2);
}

export function DeleteLayoutPreset(arg1) {
  return window['go']['main']['App']['DeleteLayoutPreset'](arg1);
}

export function DeleteScheduleGraph(arg1) {
  return window['go']['main']['App']['DeleteScheduleGraph'](arg1);
}

export function DeleteServerConfig(arg1) {
  return window['go']['main']['App']['DeleteServerConfig'](arg1);
}

export function DeleteWorld(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorld'](arg1, arg2);
}

export function DuplicateWorld(arg1, arg2, arg3) {
  return window['go']['main']['App']['DuplicateWorld'](arg1, arg2, arg3);
}

export function GetActiveLayout() {
  return window['go']['main']['App']['GetActiveLayout']();
}

export function GetActiveServerID() {
  return window['go']['main']['App']['GetActiveServerID']();
}

export function GetActiveTiles() {
  return window['go']['main']['App']['GetActiveTiles']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetBackupWorlds(arg1, arg2) {
  return window['go']['main']['App']['GetBackupWorlds'](arg1, arg2);
}

export function GetCommandButtons() {
  return window['go']['main']['App']['GetCommandButtons']();
}

export function GetConsoleHistory(arg1) {
  return window['go']['main']['App']['GetConsoleHistory'](arg1);
}

export function GetCustomCommands() {
  return window['go']['main']['App']['GetCustomCommands']();
}

export function GetLayoutPresets() {
  return window['go']['main']['App']['GetLayoutPresets']();
}

export function GetPlayerDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPlayerDetail'](arg1, arg2);
}

export function GetPlayerRoster(arg1) {
  return window['go']['main']['App']['GetPlayerRoster'](arg1);
}

export function GetPlayers(arg1) {
  return window['go']['main']['App']['GetPlayers'](arg1);
}

export function GetScheduleBlockDefs() {
  return window['go']['main']['App']['GetScheduleBlockDefs']();
}

export function GetScheduleGraphs() {
  return window['go']['main']['App']['GetScheduleGraphs']();
}

export function GetScheduleNextRuns() {
  return window['go']['main']['App']['GetScheduleNextRuns']();
}

export function GetScheduleRunHistory() {
  return window['go']['main']['App']['GetScheduleRunHistory']();
}

export function GetServerConfigs() {
  return window['go']['main']['App']['GetServerConfigs']();
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetStatsHistory(arg1) {
  return window['go']['main']['App']['GetStatsHistory'](arg1);
}

export function ImportScheduleGraphJSON(arg1) {
  return window['go']['main']['App']['ImportScheduleGraphJSON'](arg1);
}

export function KickPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['KickPlayer'](arg1, arg2, arg3);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListConfigFiles(arg1) {
  return window['go']['main']['App']['ListConfigFiles'](arg1);
}

export function ListWorlds(arg1) {
  return window['go']['main']['App']['ListWorlds'](arg1);
}

export function OpenBackupDir(arg1) {
  return window['go']['main']['App']['OpenBackupDir'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenWorldFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenWorldFolder'](arg1, arg2);
}

export function PardonPlayer(arg1, arg2) {
  return window['go']['main']['App']['PardonPlayer'](arg1, arg2);
}

export function PreviewScheduleNode(arg1, arg2) {
  return window['go']['main']['App']['PreviewScheduleNode'](arg1, arg2);
}

export function ReadConfigFile(arg1, arg2) {
  return window['go']['main']['App']['ReadConfigFile'](arg1, arg2);
}

export function RenameWorld(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameWorld'](arg1, arg2, arg3);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RunScheduleGraphNow(arg1) {
  return window['go']['main']['App']['RunScheduleGraphNow'](arg1);
}

export function SaveActiveLayout(arg1) {
  return window['go']['main']['App']['SaveActiveLayout'](arg1);
}

export function SaveActiveTiles(arg1) {
  return window['go']['main']['App']['SaveActiveTiles'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveCommandButtons(arg1) {
  return window['go']['main']['App']['SaveCommandButtons'](arg1);
}

export function SaveCustomCommands(arg1) {
  return window['go']['main']['App']['SaveCustomCommands'](arg1);
}

export function SaveLayoutPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveLayoutPreset'](arg1, arg2);
}

export function SaveScheduleGraph(arg1) {
  return window['go']['main']['App']['SaveScheduleGraph'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SetActiveServerID(arg1) {
  return window['go']['main']['App']['SetActiveServerID'](arg1);
}

export function SetActiveWorld(arg1, arg2) {
  return window['go']['main']['App']['SetActiveWorld'](arg1, arg2);
}

export function SetScheduleGraphEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetScheduleGraphEnabled'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function UpdateBackupMeta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBackupMeta'](arg1, arg2, arg3, arg4);
}

export function WriteConfigFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteConfigFile'](arg1, arg2, arg3);
}
