// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptEula(arg1:string):Promise<void>;

export function BackupWorld(arg1:string,arg2:string):Promise<models.Backup>;

export function BanPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowseDirectory():Promise<string>;

export function BrowseJarFile():Promise<string>;

export function CreateBackup(arg1:string):Promise<models.Backup>;

export function DeleteBackup(arg1:string,arg2:string):Promise<void>;

export function DeleteLayoutPreset(arg1:string):Promise<void>;

export function DeleteScheduleGraph(arg1:string):Promise<void>;

export function DeleteServerConfig(arg1:string):Promise<void>;

export function DeleteWorld(arg1:string,arg2:string):Promise<void>;

export function DuplicateWorld(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveLayout():Promise<string>;

export function GetActiveServerID():Promise<string>;

export function GetActiveTiles():Promise<Array<string>>;

export function GetAppSettings():Promise<models.AppSettings>;

export function GetCommandButtons():Promise<string>;

export function GetConsoleHistory(arg1:string):Promise<Array<models.ConsoleLine>>;

export function GetCustomCommands():Promise<Array<string>>;

export function GetLayoutPresets():Promise<Array<models.LayoutPreset>>;

export function GetPlayerDetail(arg1:string,arg2:string):Promise<models.Player>;

export function GetPlayerRoster(arg1:string):Promise<Array<models.Player>>;

export function GetPlayers(arg1:string):Promise<Array<models.Player>>;

export function GetScheduleBlockDefs():Promise<Array<models.BlockDef>>;

export function GetScheduleGraphs():Promise<Array<models.Graph>>;

export function GetScheduleNextRuns():Promise<Record<string, number>>;

export function GetScheduleRunHistory():Promise<Array<models.RunRecord>>;

export function GetServerConfigs():Promise<Array<models.ServerConfig>>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetStatsHistory(arg1:string):Promise<Array<models.StatsSnapshot>>;

export function ImportScheduleGraphJSON(arg1:string):Promise<models.Graph>;

export function KickPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListBackups(arg1:string):Promise<Array<models.Backup>>;

export function ListConfigFiles(arg1:string):Promise<Array<models.ConfigFile>>;

export function ListWorlds(arg1:string):Promise<Array<models.WorldSystem>>;

export function OpenBackupDir(arg1:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenWorldFolder(arg1:string,arg2:string):Promise<void>;

export function PardonPlayer(arg1:string,arg2:string):Promise<void>;

export function PreviewScheduleNode(arg1:models.Graph,arg2:string):Promise<models.NodePreview>;

export function ReadConfigFile(arg1:string,arg2:string):Promise<string>;

export function RenameWorld(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RunScheduleGraphNow(arg1:string):Promise<models.RunRecord>;

export function SaveActiveLayout(arg1:string):Promise<void>;

export function SaveActiveTiles(arg1:Array<string>):Promise<void>;

export function SaveAppSettings(arg1:models.AppSettings):Promise<void>;

export function SaveCommandButtons(arg1:string):Promise<void>;

export function SaveCustomCommands(arg1:Array<string>):Promise<void>;

export function SaveLayoutPreset(arg1:string,arg2:string):Promise<void>;

export function SaveScheduleGraph(arg1:models.Graph):Promise<models.Graph>;

export function SaveServerConfig(arg1:models.ServerConfig):Promise<void>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function SetActiveServerID(arg1:string):Promise<void>;

export function SetActiveWorld(arg1:string,arg2:string):Promise<void>;

export function SetScheduleGraphEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function UpdateBackupMeta(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Backup>;

export function WriteConfigFile(arg1:string,arg2:string,arg3:string):Promise<void>;
