// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BanPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['BanPlayer'](arg1, arg2, arg3);
}

export function DeleteLayoutPreset(arg1) {
  return window['go']['main']['App']['DeleteLayoutPreset'](arg1);
}

export function GetActiveTiles() {
  return window['go']['main']['App']['GetActiveTiles']();
}

export function GetCustomCommands() {
  return window['go']['main']['App']['GetCustomCommands']();
}

export function GetLayoutPresets() {
  return window['go']['main']['App']['GetLayoutPresets']();
}

export function GetPlayers(arg1) {
  return window['go']['main']['App']['GetPlayers'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function KickPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['KickPlayer'](arg1, arg2, arg3);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function SaveActiveTiles(arg1) {
  return window['go']['main']['App']['SaveActiveTiles'](arg1);
}

export function SaveCustomCommands(arg1) {
  return window['go']['main']['App']['SaveCustomCommands'](arg1);
}

export function SaveLayoutPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveLayoutPreset'](arg1, arg2);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}
