// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptEula(arg1:string):Promise<void>;

export function BanPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowseDirectory():Promise<string>;

export function BrowseJarFile():Promise<string>;

export function DeleteLayoutPreset(arg1:string):Promise<void>;

export function DeleteServerConfig(arg1:string):Promise<void>;

export function GetActiveLayout():Promise<string>;

export function GetActiveServerID():Promise<string>;

export function GetActiveTiles():Promise<Array<string>>;

export function GetAppSettings():Promise<models.AppSettings>;

export function GetCommandButtons():Promise<string>;

export function GetCustomCommands():Promise<Array<string>>;

export function GetLayoutPresets():Promise<Array<models.LayoutPreset>>;

export function GetPlayers(arg1:string):Promise<Array<models.Player>>;

export function GetServerConfigs():Promise<Array<models.ServerConfig>>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetStatsHistory(arg1:string):Promise<Array<models.StatsSnapshot>>;

export function KickPlayer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function SaveActiveLayout(arg1:string):Promise<void>;

export function SaveActiveTiles(arg1:Array<string>):Promise<void>;

export function SaveAppSettings(arg1:models.AppSettings):Promise<void>;

export function SaveCommandButtons(arg1:string):Promise<void>;

export function SaveCustomCommands(arg1:Array<string>):Promise<void>;

export function SaveLayoutPreset(arg1:string,arg2:string):Promise<void>;

export function SaveServerConfig(arg1:models.ServerConfig):Promise<void>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function SetActiveServerID(arg1:string):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;
